
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed4;

	private global::Gtk.Label lblName;

	private global::Gtk.Entry txtDescription;

	private global::Gtk.Entry txtQuantity;

	private global::Gtk.Entry txtPrice;

	private global::Gtk.Label lblDescription;

	private global::Gtk.Label lblQuantity;

	private global::Gtk.Label lblPrice;

	private global::Gtk.Entry txtName;

	private global::Gtk.Label lblCode;

	private global::Gtk.Button btnDelete;

	private global::Gtk.Button btnSearch;

	private global::Gtk.Entry txtCode;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.Button btnList;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView txtList;

	private global::Gtk.Button btnAdd;

	private global::Gtk.Button btnInsert;

	private global::Gtk.Label lblPos;

	private global::Gtk.Entry txtPos;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed4 = new global::Gtk.Fixed();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.lblName = new global::Gtk.Label();
		this.lblName.Name = "lblName";
		this.lblName.Xpad = 1;
		this.lblName.Ypad = 1;
		this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
		this.lblName.Justify = ((global::Gtk.Justification)(2));
		this.fixed4.Add(this.lblName);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.lblName]));
		w1.X = 49;
		w1.Y = 28;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.txtDescription = new global::Gtk.Entry();
		this.txtDescription.WidthRequest = 370;
		this.txtDescription.CanFocus = true;
		this.txtDescription.Name = "txtDescription";
		this.txtDescription.IsEditable = true;
		this.txtDescription.InvisibleChar = '•';
		this.fixed4.Add(this.txtDescription);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.txtDescription]));
		w2.X = 118;
		w2.Y = 71;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.txtQuantity = new global::Gtk.Entry();
		this.txtQuantity.CanFocus = true;
		this.txtQuantity.Name = "txtQuantity";
		this.txtQuantity.IsEditable = true;
		this.txtQuantity.InvisibleChar = '•';
		this.fixed4.Add(this.txtQuantity);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.txtQuantity]));
		w3.X = 117;
		w3.Y = 121;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.txtPrice = new global::Gtk.Entry();
		this.txtPrice.CanFocus = true;
		this.txtPrice.Name = "txtPrice";
		this.txtPrice.IsEditable = true;
		this.txtPrice.InvisibleChar = '•';
		this.fixed4.Add(this.txtPrice);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.txtPrice]));
		w4.X = 115;
		w4.Y = 173;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.lblDescription = new global::Gtk.Label();
		this.lblDescription.Name = "lblDescription";
		this.lblDescription.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion");
		this.fixed4.Add(this.lblDescription);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.lblDescription]));
		w5.X = 36;
		w5.Y = 82;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.lblQuantity = new global::Gtk.Label();
		this.lblQuantity.Name = "lblQuantity";
		this.lblQuantity.LabelProp = global::Mono.Unix.Catalog.GetString("Cantidad");
		this.fixed4.Add(this.lblQuantity);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.lblQuantity]));
		w6.X = 46;
		w6.Y = 128;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.lblPrice = new global::Gtk.Label();
		this.lblPrice.Name = "lblPrice";
		this.lblPrice.LabelProp = global::Mono.Unix.Catalog.GetString("Costo");
		this.fixed4.Add(this.lblPrice);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.lblPrice]));
		w7.X = 61;
		w7.Y = 180;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.txtName = new global::Gtk.Entry();
		this.txtName.WidthRequest = 370;
		this.txtName.CanFocus = true;
		this.txtName.Name = "txtName";
		this.txtName.IsEditable = true;
		this.txtName.InvisibleChar = '•';
		this.fixed4.Add(this.txtName);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.txtName]));
		w8.X = 119;
		w8.Y = 25;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.lblCode = new global::Gtk.Label();
		this.lblCode.Name = "lblCode";
		this.lblCode.LabelProp = global::Mono.Unix.Catalog.GetString("Codigo");
		this.fixed4.Add(this.lblCode);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.lblCode]));
		w9.X = 49;
		w9.Y = 259;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.btnDelete = new global::Gtk.Button();
		this.btnDelete.WidthRequest = 80;
		this.btnDelete.CanFocus = true;
		this.btnDelete.Name = "btnDelete";
		this.btnDelete.UseUnderline = true;
		this.btnDelete.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
		this.fixed4.Add(this.btnDelete);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.btnDelete]));
		w10.X = 415;
		w10.Y = 252;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.btnSearch = new global::Gtk.Button();
		this.btnSearch.WidthRequest = 80;
		this.btnSearch.CanFocus = true;
		this.btnSearch.Name = "btnSearch";
		this.btnSearch.UseUnderline = true;
		this.btnSearch.Label = global::Mono.Unix.Catalog.GetString("Buscar");
		this.fixed4.Add(this.btnSearch);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.btnSearch]));
		w11.X = 312;
		w11.Y = 252;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.txtCode = new global::Gtk.Entry();
		this.txtCode.CanFocus = true;
		this.txtCode.Name = "txtCode";
		this.txtCode.IsEditable = true;
		this.txtCode.InvisibleChar = '•';
		this.fixed4.Add(this.txtCode);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.txtCode]));
		w12.X = 115;
		w12.Y = 249;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.WidthRequest = 500;
		this.hseparator2.Name = "hseparator2";
		this.fixed4.Add(this.hseparator2);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.hseparator2]));
		w13.X = 25;
		w13.Y = 224;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.HeightRequest = 300;
		this.vseparator1.Name = "vseparator1";
		this.fixed4.Add(this.vseparator1);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.vseparator1]));
		w14.X = 542;
		w14.Y = 10;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.btnList = new global::Gtk.Button();
		this.btnList.WidthRequest = 80;
		this.btnList.CanFocus = true;
		this.btnList.Name = "btnList";
		this.btnList.UseUnderline = true;
		this.btnList.Label = global::Mono.Unix.Catalog.GetString("Listar");
		this.fixed4.Add(this.btnList);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.btnList]));
		w15.X = 570;
		w15.Y = 8;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.WidthRequest = 400;
		this.GtkScrolledWindow.HeightRequest = 270;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtList = new global::Gtk.TextView();
		this.txtList.CanFocus = true;
		this.txtList.Name = "txtList";
		this.txtList.Editable = false;
		this.txtList.CursorVisible = false;
		this.GtkScrolledWindow.Add(this.txtList);
		this.fixed4.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.GtkScrolledWindow]));
		w17.X = 560;
		w17.Y = 50;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.btnAdd = new global::Gtk.Button();
		this.btnAdd.WidthRequest = 80;
		this.btnAdd.CanFocus = true;
		this.btnAdd.Name = "btnAdd";
		this.btnAdd.UseUnderline = true;
		this.btnAdd.Label = global::Mono.Unix.Catalog.GetString("Agregar");
		this.fixed4.Add(this.btnAdd);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.btnAdd]));
		w18.X = 311;
		w18.Y = 121;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.btnInsert = new global::Gtk.Button();
		this.btnInsert.WidthRequest = 80;
		this.btnInsert.CanFocus = true;
		this.btnInsert.Name = "btnInsert";
		this.btnInsert.UseUnderline = true;
		this.btnInsert.Label = global::Mono.Unix.Catalog.GetString("Insertar");
		this.fixed4.Add(this.btnInsert);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.btnInsert]));
		w19.X = 310;
		w19.Y = 171;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.lblPos = new global::Gtk.Label();
		this.lblPos.Name = "lblPos";
		this.lblPos.LabelProp = global::Mono.Unix.Catalog.GetString("Posicion");
		this.fixed4.Add(this.lblPos);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.lblPos]));
		w20.X = 399;
		w20.Y = 182;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.txtPos = new global::Gtk.Entry();
		this.txtPos.WidthRequest = 70;
		this.txtPos.CanFocus = true;
		this.txtPos.Name = "txtPos";
		this.txtPos.IsEditable = true;
		this.txtPos.InvisibleChar = '•';
		this.fixed4.Add(this.txtPos);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.txtPos]));
		w21.X = 460;
		w21.Y = 173;
		this.Add(this.fixed4);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 983;
		this.DefaultHeight = 336;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnDelete.Clicked += new global::System.EventHandler(this.BtnDeleteClick);
		this.btnSearch.Clicked += new global::System.EventHandler(this.BtnSearchClick);
		this.btnList.Clicked += new global::System.EventHandler(this.BtnListClick);
		this.btnAdd.Clicked += new global::System.EventHandler(this.BtnAddClick);
		this.btnInsert.Clicked += new global::System.EventHandler(this.BtnInsertClick);
	}
}
